version: 2
updates:
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend-minor-patches:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /city-cleanup-challenge
    schedule:
      interval: weekly
    groups:
      frontend-minor-patches:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /city-cleanup-challenge
    schedule:
      interval: weekly
