CREATE TABLE IF NOT EXISTS subscriptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price DOUBLE PRECISION NOT NULL DEFAULT 0,
  features TEXT
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  email TEXT UNIQUE,
  phone TEXT,
  location TEXT,
  role TEXT NOT NULL DEFAULT 'user',
  avatar TEXT,
  celo_wallet_address TEXT,
  celo_wallet_verified_at TIMESTAMPTZ,
  subscription_id INTEGER REFERENCES subscriptions(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  replaced_by_hash TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  content TEXT NOT NULL,
  createdat TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cleanup_plans (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  code TEXT NOT NULL UNIQUE,
  area TEXT,
  targetwaste DOUBLE PRECISION,
  estimatedduration INTEGER,
  difficulty TEXT,
  status TEXT,
  createdby TEXT,
  createdat TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedat TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usage_analytics (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userid INTEGER,
  username TEXT,
  action TEXT NOT NULL,
  target TEXT,
  details TEXT,
  ipaddress TEXT,
  useragent TEXT,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sessionid TEXT
);

CREATE TABLE IF NOT EXISTS events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  location TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  date TEXT,
  time TEXT,
  creator TEXT,
  createdat TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status TEXT
);

CREATE TABLE IF NOT EXISTS event_checkins (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  eventid INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  username TEXT NOT NULL,
  checkintime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS cleanup_progress (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  eventid INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  username TEXT NOT NULL,
  wastecollected DOUBLE PRECISION,
  wastetype TEXT,
  beforephotopath TEXT,
  afterphotopath TEXT,
  notes TEXT,
  beforephotogps TEXT,
  afterphotogps TEXT,
  impactanalysis TEXT,
  updatedat TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (eventid, username)
);

CREATE TABLE IF NOT EXISTS cleanup_submissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  waste_category TEXT NOT NULL,
  item_count INTEGER,
  estimated_weight DOUBLE PRECISION,
  notes TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  location_accuracy DOUBLE PRECISION NOT NULL,
  captured_before_at TIMESTAMPTZ,
  captured_after_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'pending',
  duplicate_of INTEGER REFERENCES cleanup_submissions(id),
  verification_summary TEXT,
  verification_version TEXT,
  risk_level TEXT,
  rejection_reason TEXT,
  appeal_reason TEXT,
  appealed_at TIMESTAMPTZ,
  reviewed_by INTEGER REFERENCES users(id),
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cleanup_evidence_files (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id INTEGER NOT NULL REFERENCES cleanup_submissions(id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK (kind IN ('before', 'after')),
  storage_path TEXT NOT NULL,
  sha256 TEXT NOT NULL,
  perceptual_hash TEXT,
  image_metadata TEXT,
  mime_type TEXT NOT NULL,
  byte_size INTEGER NOT NULL,
  original_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (submission_id, kind)
);

CREATE TABLE IF NOT EXISTS submission_transitions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id INTEGER NOT NULL REFERENCES cleanup_submissions(id) ON DELETE CASCADE,
  actor_user_id INTEGER REFERENCES users(id),
  from_status TEXT,
  to_status TEXT NOT NULL,
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reward_payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_id TEXT NOT NULL UNIQUE,
  submission_id INTEGER NOT NULL UNIQUE REFERENCES cleanup_submissions(id),
  user_id INTEGER NOT NULL REFERENCES users(id),
  wallet_address TEXT,
  policy_version TEXT NOT NULL,
  calculation TEXT NOT NULL,
  amount_wei TEXT NOT NULL,
  status TEXT NOT NULL,
  chain_id INTEGER,
  contract_address TEXT,
  transaction_hash TEXT UNIQUE,
  block_number INTEGER,
  attempts INTEGER NOT NULL DEFAULT 0,
  failure_code TEXT,
  failure_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  broadcast_at TIMESTAMPTZ,
  confirmed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS wallet_verification_challenges (
  id TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  wallet_address TEXT NOT NULL,
  message TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reward_controls (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  paused INTEGER NOT NULL DEFAULT 1,
  pause_reason TEXT,
  updated_by INTEGER REFERENCES users(id),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reward_audit_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id INTEGER REFERENCES reward_payments(id),
  actor_user_id INTEGER REFERENCES users(id),
  action TEXT NOT NULL,
  from_status TEXT,
  to_status TEXT,
  details TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_cleanup_submissions_user ON cleanup_submissions(user_id);
CREATE INDEX IF NOT EXISTS idx_cleanup_submissions_status ON cleanup_submissions(status);
CREATE INDEX IF NOT EXISTS idx_cleanup_evidence_sha256 ON cleanup_evidence_files(sha256);
CREATE INDEX IF NOT EXISTS idx_cleanup_evidence_phash ON cleanup_evidence_files(perceptual_hash);
CREATE INDEX IF NOT EXISTS idx_submission_transitions_submission ON submission_transitions(submission_id);
CREATE INDEX IF NOT EXISTS idx_reward_payments_status ON reward_payments(status);
CREATE INDEX IF NOT EXISTS idx_reward_payments_user ON reward_payments(user_id);
CREATE INDEX IF NOT EXISTS idx_wallet_challenges_user ON wallet_verification_challenges(user_id);
CREATE INDEX IF NOT EXISTS idx_reward_audit_payment ON reward_audit_log(payment_id);
CREATE INDEX IF NOT EXISTS idx_usage_analytics_timestamp ON usage_analytics(timestamp);

INSERT INTO reward_controls (id, paused, pause_reason)
VALUES (1, 1, 'Rewards remain paused until an administrator enables payouts')
ON CONFLICT (id) DO NOTHING;
