CREATE TABLE IF NOT EXISTS system_audit_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  actor_username TEXT,
  category TEXT NOT NULL CHECK (
    category IN ('authentication', 'administration', 'moderation', 'destructive')
  ),
  action TEXT NOT NULL,
  outcome TEXT NOT NULL CHECK (outcome IN ('success', 'failure')),
  request_id TEXT NOT NULL,
  request_method TEXT NOT NULL,
  request_path TEXT NOT NULL,
  response_status INTEGER NOT NULL,
  ip_hash TEXT,
  user_agent_hash TEXT,
  details TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_system_audit_created
  ON system_audit_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_audit_category_created
  ON system_audit_events(category, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_audit_actor_created
  ON system_audit_events(actor_user_id, created_at DESC);
